### PR TITLE
libndp: fix type of field "na" in "struct ndp_msgna"

### PR DESCRIPTION
**Pull request by thom311**
Otherwise, compilation fails since commit cb1ab5fc8b:

   libndp.c: In function ‘ndp_msgna_flag_router’:
   libndp.c:992:18: error: ‘struct nd_neighbor_solicit’ has no member named ‘nd_na_hdr’
     return msgna->na->nd_na_flags_reserved & ND_NA_FLAG_ROUTER;

Fixes: dfed476eee192e86c140298810bb598c927645e8
Signed-off-by: Thomas Haller <thaller@redhat.com>

### CODE REVIEW

**Comment by thom311** [comment]
Patch already applied: https://github.com/jpirko/libndp/commit/d0ea3eccf42e4cec59b057474f844fc4f616d4de
